//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckCollect
    {
        public int checkCollect_CollectId { get; set; }
        public Nullable<int> checkCollect_StartId { get; set; }
        public string checkCollect_factoryId { get; set; }
        public string checkCollect_cancel { get; set; }
        public string checkCollect_comfirm { get; set; }
        public Nullable<System.DateTime> checkCollect_confirmTime { get; set; }
        public string checkCollect_mail { get; set; }
        public Nullable<System.DateTime> checkCollect_mailTime { get; set; }
    
        public virtual StartCheck StartCheck { get; set; }
        public virtual Factory Factory { get; set; }
    }
}
