//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckItem
    {
        public int checkItem_itemId { get; set; }
        public string checkItem_reportId { get; set; }
        public string checkItem_itemCode { get; set; }
        public string checkItem_itemName { get; set; }
        public Nullable<double> checkItem_itemValue { get; set; }
        public string checkItem_IsOK { get; set; }
        public string checkItem_description { get; set; }
        public string checkItem_updateUser { get; set; }
        public Nullable<System.DateTime> checkItem_updateDate { get; set; }
    
        public virtual ReportManage ReportManage { get; set; }
    }
}
