//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeWork
    {
        public int Id { get; set; }
        public string employee_workNumber { get; set; }
        public Nullable<int> employee_Workid { get; set; }
        public string workId_isDisable { get; set; }
        public string emp_workupdateUser { get; set; }
        public Nullable<System.DateTime> emp_workupdateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual WorkInfo WorkInfo { get; set; }
    }
}
