//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartFile
    {
        public int startFile_fileId { get; set; }
        public int start_id { get; set; }
        public string startFile_name { get; set; }
        public string startFile_content { get; set; }
    
        public virtual StartCheck StartCheck { get; set; }
    }
}
