//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartPlace
    {
        public int startPlace_id { get; set; }
        public string startPlace_factoryId { get; set; }
        public int startplace_startId { get; set; }
    
        public virtual Factory Factory { get; set; }
        public virtual StartCheck StartCheck { get; set; }
    }
}
