//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authority
    {
        public int authority_Id { get; set; }
        public string authority_workNumber { get; set; }
        public string authority_factoryId { get; set; }
        public string authority_IsDisable { get; set; }
        public string authority_role { get; set; }
        public string authority_updateuser { get; set; }
        public Nullable<System.DateTime> authority_updateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
