//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoubleCheck
    {
        public int doubleCheck_itemId { get; set; }
        public Nullable<int> doubleCheck_reportId { get; set; }
        public string doubleCheck_itemCode { get; set; }
        public string doubleCheck_itemName { get; set; }
        public Nullable<double> doubleCheck_itemValue { get; set; }
        public string doubleCheck_IsOK { get; set; }
        public string doubleCheck_description { get; set; }
        public Nullable<System.DateTime> doubleCheck_date { get; set; }
        public string doubleCheck_updateUser { get; set; }
        public Nullable<System.DateTime> doubleCheck_updateDate { get; set; }
    
        public virtual ReportManage ReportManage { get; set; }
    }
}
