//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectPerson
    {
        public int inspectPerson_listId { get; set; }
        public string inspectPerson_WorkNumber { get; set; }
        public string inspectPerson_newWork { get; set; }
        public string inspectPerson_role { get; set; }
        public string inspectPerson_bookNumber { get; set; }
        public string inspectPerson_source { get; set; }
        public string inspectPerson_updateUser { get; set; }
        public Nullable<System.DateTime> inspectPerson_updateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
