//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.book = new HashSet<book>();
            this.book1 = new HashSet<book>();
            this.ReportManage = new HashSet<ReportManage>();
        }
    
        public int program_programId { get; set; }
        public int program_hospitalId { get; set; }
        public string program_programName { get; set; }
        public string program_content { get; set; }
        public int program_workid { get; set; }
        public string program_state { get; set; }
        public string program_updateuser { get; set; }
        public Nullable<System.DateTime> program_updatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book> book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book> book1 { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual WorkInfo WorkInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportManage> ReportManage { get; set; }
    }
}
