//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportFile
    {
        public int reportFile_fileId { get; set; }
        public Nullable<int> reportFile_reportId { get; set; }
        public string reportFile_name { get; set; }
        public string reportFile_content { get; set; }
    
        public virtual ReportManage ReportManage { get; set; }
    }
}
