//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportManage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportManage()
        {
            this.CheckItem = new HashSet<CheckItem>();
            this.DoubleCheck = new HashSet<DoubleCheck>();
            this.ReportFile = new HashSet<ReportFile>();
        }
    
        public int ReportManage_id { get; set; }
        public string ReportManage_workNumber { get; set; }
        public Nullable<int> ReportManage_startId { get; set; }
        public Nullable<int> ReportManage_hospitalId { get; set; }
        public int ReportManage_programId { get; set; }
        public string ReportManage_medicalRecord { get; set; }
        public Nullable<System.DateTime> ReportManage_healthDate { get; set; }
        public string ReportManage_corporation { get; set; }
        public string ReportManage_IsdoubleCheck { get; set; }
        public string ReportManage_hw { get; set; }
        public string ReportManage_pastHistory { get; set; }
        public string ReportManage_symptoms { get; set; }
        public string ReportManage_notes { get; set; }
        public string ReportManage_IsDisable { get; set; }
        public Nullable<int> ReportManage_doubleId { get; set; }
        public string ReportManage_updateUser { get; set; }
        public Nullable<System.DateTime> ReportManage_updateTime { get; set; }
        public string generalComment_1 { get; set; }
        public string generalComment_2 { get; set; }
        public string generalComment_3 { get; set; }
        public string generalComment_4 { get; set; }
        public string generalComment_5 { get; set; }
        public string generalComment_6 { get; set; }
        public string generalComment_7 { get; set; }
        public string generalComment_8 { get; set; }
        public string generalComment_9 { get; set; }
        public string generalComment_10 { get; set; }
        public string generalComment_11 { get; set; }
        public string generalComment_12 { get; set; }
        public string generalComment_13 { get; set; }
        public string generalComment_14 { get; set; }
        public string generalComment_15 { get; set; }
        public string generalComment_16 { get; set; }
        public string generalComment_17 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckItem> CheckItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoubleCheck> DoubleCheck { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportFile> ReportFile { get; set; }
        public virtual StartCheck StartCheck { get; set; }
    }
}
