//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EmpAuthFa
    {
        public string employee_workNumber { get; set; }
        public string employee_role { get; set; }
        public string employee_name { get; set; }
        public string employee_username { get; set; }
        public string employee_isDisabled { get; set; }
        public string authority_factoryId { get; set; }
        public string authority_IsDisable { get; set; }
        public string factory_area { get; set; }
        public string factory_name { get; set; }
        public string factory_id { get; set; }
        public int Id { get; set; }
    }
}
