//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HospitalProgram
    {
        public int program_programId { get; set; }
        public string hospital_name { get; set; }
        public string hospital_address { get; set; }
        public string hospital_contact { get; set; }
        public string hospital_phone { get; set; }
        public string hospital_uniform { get; set; }
        public string hospital_website { get; set; }
        public string hospital_email { get; set; }
        public string hospital_state { get; set; }
        public string hospital_updateuser { get; set; }
        public Nullable<System.DateTime> hospital_updatetime { get; set; }
        public string program_programName { get; set; }
        public string program_content { get; set; }
        public string work_name { get; set; }
        public string program_state { get; set; }
        public string program_updateuser { get; set; }
        public Nullable<System.DateTime> program_updatetime { get; set; }
    }
}
